language: php
php:
  - '7.0'

install:
  - composer self-update
  - make install

script: make lint test

addons:
  code_climate:
    repo_token: e19245d8f28a2dec47efbe52bae2785e5bbd168c74d6310e7268e796b07972dc

after_script:
  - vendor/bin/test-reporter
